{% set version = "5fa5db0" %}
package:
    name: visionworkbench
    version: {{ version }}

source:
  git_url: git@github.com:visionworkbench/visionworkbench.git
  git_tag: {{ version }}

build:
    number: 0

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
    host:
        - gdal                      2.0.2
        - ilmbase
        - openexr
        - eigen
        - pbzip2
        - gflags
        - glog
        - ceres-solver
        - parallel
        - flann                     1.9.*
        - opencv                    3.*
        - boost                     1.68
        - liblapack
        - blas
        - geotiff                   1.4.2
        - proj4                     4.9.3
        - geos                      3.7.3
        - hdf5                      1.8.*

    run:
        - gdal                      2.0.2
        - ilmbase
        - openexr
        - eigen
        - pbzip2
        - gflags
        - glog
        - ceres-solver
        - parallel
        - flann                     1.9.*
        - opencv                    3.*
        - boost                     1.68
        - liblapack
        - blas
        - geotiff                   1.4.2
        - proj4                     4.9.3
        - geos                      3.7.3
        - hdf5                      1.8.*

test:
    files:
        imports:
        commands:
        comment: "Add here something like hillshade --help"

about:
    home: https://github.com/visionworkbench/visionworkbench
    license: Apache II
    summary: 

extra:
  recipe-maintainers:
    - olegalexandrov
