# Ensure that the VW and ASP meta.yaml files are in sync with each other and with 
# ISIS. 
# Specify the correct tag in git_tag, for example, 3.3.0, or a commit hash.
{% set version = "3.3.0" %}

package:
    name: visionworkbench
    version: {{ version }}

source:
  git_url: git@github.com:visionworkbench/visionworkbench.git
# No git tag. Just built latest. More convenient this way.  
#  git_tag: {{ version }}

build:
    number: 0

requirements:
    build:
        - {{ compiler('c') }} 
        - {{ compiler('cxx') }}
        - cmake 3.15.5
        
    host:
        - libgdal                   3.5_isis8
        - llvm-openmp               16.0.6
        - ilmbase                   2.5.5
        - openexr                   2.5.5
        - flann                     1.9.1
        - opencv                    4.5.5
        - openssl                   1.1.1v
        - libssh2                   1.10.0
        - boost                     1.72.0
        - openblas
        - liblapack                 3.9.0
        - blas                      2.117
        - proj                      9.1.0
        - hdf5                      1.12.1
  
    run:
        - libgdal                   3.5_isis8
        - llvm-openmp               16.0.6
        - ilmbase                   2.5.5
        - openexr                   2.5.5
        - flann                     1.9.1
        - opencv                    4.5.5
        - openssl                   1.1.1v
        - libssh2                   1.10.0
        - boost                     1.72.0
        - openblas
        - liblapack                 3.9.0
        - blas                      2.117
        - proj                      9.1.0
        - hdf5                      1.12.1

test:
    files:
        imports:
        commands:
        comment: "Add here something like hillshade --help"

about:
    home: https://github.com/visionworkbench/visionworkbench
    license: APACHE
    summary: A general purpose image processing and computer vision library

extra:
  recipe-maintainers:
    - olegalexandrov
