{% set version = "2.6.2" %}
package:
    name: visionworkbench
    version: {{ version }}

source:
    fn: {{ version }}.tar.gz
    url: https://github.com/visionworkbench/visionworkbench/archive/{{ version }}.tar.gz
    sha256sum: 9703e130b2c100b8aafbce64d8f57c98d5d7895f02c40633346e8eee521e8fbb

build:
    number: 0

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
    host:
        - gdal                      2.0.2
        - ilmbase
        - openexr
        - eigen
        - pbzip2
        - gflags
        - glog
        - ceres-solver
        - parallel
        - flann                     1.9.*
        - opencv                    3.*
        - boost                     1.68
        - liblapack
        - blas
    run:
        - gdal                      2.0.2
        - ilmbase
        - openexr
        - eigen
        - pbzip2
        - gflags
        - glog
        - ceres-solver
        - parallel
        - flann                     1.9.*
        - opencv                    3.*
        - boost                     1.68
        - liblapack
        - blas

test:
    files:
        imports:
        commands:
        comment: "Add here something like hillshade --help"

about:
    home: https://github.com/visionworkbench/visionworkbench
    license: Apache II
    summary: 

extra:
  recipe-maintainers:
    - olegalexandrov
